### ISSUE TITLE
Sensor / led / motor speed values not showing in Scratch

### ISSUE THREAD

**Issue by ddoak** [davidjsherman/inirobot-scratch-thymioII#3]
Just quickly tried 0.7 with a USB tethered thymio.
I can set led colours / motor speeds etc. However none of the readings (grey lozenge blocks) report any values. 
However, the button boolean *is* working (i.e. correctly reporting true/false)

![screen shot 2016-04-08 at 14 42 52](https://cloud.githubusercontent.com/assets/7423291/14385419/591f5492-fd98-11e5-808b-ebbd843d7262.png)

**Comment by davidjsherman** [comment]
You actually need to use Scratch v445.1, but from the image I can see that you are using Scratch v445. Unfortunately their automatic check for updates doesn't pick up the minor version bump. The links on the page https://scratch.mit.edu/scratch2download/ are correct, though.

The direct download links are
- MacOS https://scratch.mit.edu/scratchr2/static/sa/Scratch-445.1.dmg
- Windows https://scratch.mit.edu/scratchr2/static/sa/Scratch-445.1.exe

Could you please check that this solves your problem? Thanks

(I'm afraid that [LLK/scratch-flash](https://github.com/LLK/scratch-flash) has been a bit of a moving target.)

**Comment by davidjsherman** [comment]
By the way, this only happens for reporters with menus. You shouldn't see this problem with `loudness`, for example. So I believe that this is a duplicate of issue #2.

**Comment by ddoak** [comment]
Checked and working correctly in Scratch v445.1 (my mistake, I didn't read the release notes and assumed the Scratch updater would install the latest version.)
